version: '3.8'
services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Direct mount of Let's Encrypt certs
    depends_on:
      - myflashpal-frontend



  myflashpal-frontend:
    build:
      context: ./sites/myflashpal/react-app
      dockerfile: ../../../docker/myflashpal/react-app.Dockerfile
    depends_on:
      - myflashpal-backend

  myflashpal-backend:
    build:
      context: ./sites/myflashpal/server
      dockerfile: ../../../docker/myflashpal/server.Dockerfile
    environment:
      - DOCKER_ENV=true
    env_file:
      - ./sites/myflashpal/server/.env
    volumes:
      - ./sites/myflashpal/server/X509-cert-1753682967918674388.pem:/certs/X509-cert-1753682967918674388.pem



  lonestarstatuary-frontend:
    build:
      context: ./sites/lonestarstatuary/react-app
      dockerfile: ../../../docker/lonestarstatuary/react-app.Dockerfile
    depends_on:
      - lonestarstatuary-backend

  lonestarstatuary-backend:
    build:
      context: ./sites/lonestarstatuary/server
      dockerfile: ../../../docker/lonestarstatuary/server.Dockerfile
    environment:
      - DOCKER_ENV=true
    # env_file commented out until needed
    # env_file:
    #   - ./sites/lonestarstatuary/server/.env
    


  boilerplate-frontend:
    build:
      context: ./sites/boilerplate/react-app
      dockerfile: ../../../docker/boilerplate/react-app.Dockerfile
    depends_on:
      - boilerplate-backend

  boilerplate-backend:
    build:
      context: ./sites/boilerplate/server
      dockerfile: ../../../docker/boilerplate/server.Dockerfile
    environment:
      - DOCKER_ENV=true
    # env_file commented out until needed
    # env_file:
    #   - ./sites/boilerplate/server/.env
